FROM debian:bookworm

WORKDIR /workspace

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y \
        python3 \
        python3-distro \
        python3-venv \
        python3-pip \
        python3-setuptools \
        binutils \
        build-essential \
        curl \
        sudo \
        && \
    apt-get clean

COPY . ./

RUN ./cerbero-uninstalled -c config/cross-android-universal.cbc bootstrap -y

RUN ./cerbero-uninstalled -c config/cross-android-universal.cbc package --only-build-deps gstreamer-1.0
